SELECT * FROM TITANIC;

SELECT COUNT(*) FROM titanic WHERE CABIN='';

SELECT COUNT(*) FROM titanic WHERE AGE='';

SELECT COUNT(*) FROM titanic WHERE FARE='';

DESC TITANIC;

UPDATE titanic SET FARE=34 WHERE FARE IS NULL;

#DECRESE THE FARE PRICE FOR PCLASS 1 BY 30%
UPDATE titanic SET FARE = FARE-(FARE*0.3) WHERE PCLASS=1;

#CREATE A NEW COLUMN CALLED FAREPRICE(INR) WITH INR CURRENCY VALUES.
ALTER TABLE titanic ADD COLUMN FAREPRICE_INR FLOAT;
UPDATE TITANIC SET FAREPRICE_INR=FARE*82;
SELECT * FROM TITANIC;

SELECT * FROM TITANIC where CABIN='C85';


SELECT COUNT(*) FROM TITANIC WHERE CABIN_CLASS ='A'
AND SURVIVED=0;



#INPLACE OF 0 WRITE NOT SURVIVED AND SURVIVED INPLACE OF 1.

# DO LITTLE ANALYSIS WHICH CABIN PEOPLE ARE PAYING MORE IS THERE IS ANY PATTERN.
SELECT *,LEFT(CABIN,1) FROM TITANIC WHERE CABIN !=''
AND SURVIVED=1;

#ADDING A COLUMN
ALTER table TITANIC ADD COLUMN CABIN_CLASS char;
UPDATE TITANIC SET CABIN_CLASS=LEFT(CABIN,1);
SELECT * FROM TITANIC;