use gfgda3;

create table emp(
	eid int PRIMARY KEY auto_increment,
    ename char(10) CHECK(LENGTH(ENAME>=3)),
    salary FLOAT CHECK(SALARY BETWEEN 1000 AND 5000),
    CITY VARCHAR(40) DEFAULT "HYDERABAD"
);

insert into emp values(1,"JHON",6000);
INSERT INTO EMP VALUES(1,"PAUL",7000);
INSERT INTO EMP(ENAME,SALARY) VALUES("HALL",6000);
SELECT * FROM EMP;


CREATE TABLE STAFF(
	ST_ID INT,
    ST_NAME CHAR(5),
    SALARY INT,
    UNIQUE KEY(ST_ID,ST_NAME)

);
DESC STAFF;
SELECT * FROM STAFF;

INSERT INTO STAFF(ST_NAME,SALARY) VALUES("PAUL",7000);

DROP TABLE EMP;





CREATE TABLE EVENT(
	EVENT_ID INT PRIMARY KEY auto_increment,
    NAME CHAR(50) CHECK(NAME LIKE "MR%" OR"MRS%"),
    LOCATION ENUM("HYDERABAD" , "DELHI"),
    STATUS ENUM("IN" , "OUT","NOT PERMITED") DEFAULT "NOT PERMITED",
    PRICE FLOAT CHECK(PRICE>=100)
    GROUP_NAME 
    );

DROP TABLE EVENT;

DESC EVENT;

INSERT INTO EVENT(NAME,LOCATION,PRICE) VALUES("MR JHON","HYDERABAD",120);