CREATE TABLE CUSTOMER(
	CUSTOMER_ID INT PRIMARY KEY AUTO_INCREMENT,
    CUSTOMER_NAME CHAR(50),
    CUSTOMER_ADDRESS VARCHAR(100) unique
);


CREATE TABLE ORDERS(
	ORDER_ID INT PRIMARY KEY,
    PID INT,
    CID INT,
    DELIVARY_ADDRESS VARCHAR(100),
	FOREIGN KEY(CID) REFERENCES CUSTOMER(CUSTOMER_ID),
    FOREIGN KEY(PID) REFERENCES PRODUCTS(PRODUCT_ID),
    FOREIGN KEY(DELIVARY_ADDRESS) REFERENCES CUSTOMER(CUSTOMER_ADDRESS)
    );

CREATE TABLE PRODUCTS(
	PRODUCT_ID INT PRIMARY KEY,
    PRODUCT_NAME  VARCHAR(50),
    PRODUCT_DECRIPTION VARCHAR(100),
    PRICE INT
);




DESC CUSTOMER;
DESC ORDERS;
DESC PRODUCTS;



select * from CUSTOMER;
select * from PRODUCTS;
select * from ORDERS;


INSERT INTO CUSTOMER VALUES(1,"ABHI","1-183");
INSERT INTO CUSTOMER VALUES(2,"BHANU","2-678");
INSERT INTO CUSTOMER VALUES(3,"CHANDU","2-345");

INSERT INTO PRODUCTS VALUES(1,"PEN","BLUE INK PEN.",5);
INSERT INTO PRODUCTS VALUES(2,"CHAIR","A PLASTIC CHAIR.",500);

INSERT INTO ORDERS VALUES(10001,2,3,"2-345");
INSERT INTO ORDERS VALUES(10002,1,1,"1-183");


USE GFGDA3;
DROP TABLE STUDENTS,EMPLOYEES,SUBJECTS,FEE_TRANSACTIONS,SALARY_TRANSACTIONS,DEPARTMENTS;
DROP TABLE DEPARTMENTS;
