SELECT * FROM DATA;

#TOP 5 BRANDS HAVING MOST PRODUCTS.
SELECT BRAND_TAG,COUNT(PRODUCT_TAG) AS 'NO_OF_PRODUCTS' FROM DATA
GROUP BY BRAND_TAG
ORDER BY NO_OF_PRODUCTS DESC limit 5;

#FIND THE TOP 10 BEST-SELLING PRODUCTS BY BRAND.

SELECT BRAND_TAG,PRODUCT_TAG,SUM(RATING_COUNT) AS 'PRODUCTS_SOLD' FROM DATA 
GROUP BY BRAND_TAG, PRODUCT_TAG
ORDER BY PRODUCTS_SOLD DESC ;

#IN ROADSTAR WHAT ARE THE NO OF PRODUCTS THHAT ARE RATED IN TSHIRTS AND JEANS.

SELECT BRAND_TAG,PRODUCT_TAG,SUM(RATING_COUNT) AS 'PRODUCTS_SOLD' FROM DATA 
WHERE BRAND_TAG = 'ROADSTER' AND PRODUCT_TAG IN ('JEANS' , 'TSHIRTS')
GROUP BY BRAND_TAG, PRODUCT_TAG
ORDER BY PRODUCTS_SOLD DESC ;

SELECT BRAND_TAG,PRODUCT_TAG, SUM(RATING_COUNT) AS 'PEOPLE_RATED',AVG(DISCOUNTED_PRICE) AS 'AVG_PRICE' FROM DATA
WHERE PRODUCT_TAG = 'TSHIRTS'
GROUP BY BRAND_TAG
ORDER BY PEOPLE_RATED DESC LIMIT 10;

