SELECT * FROM CUSTOMERS;
SELECT * FROM DEPARTMENTS;
SELECT * FROM EMPLOYEES;
SELECT * FROM ORDER_ITEMS;
SELECT * FROM ORDERS;
SELECT * FROM PRODUCTS;

SELECT FIRST_NAME,LAST_NAME,DEPARTMENT_NAME
FROM COMPANY.EMPLOYEES AS EMP
INNER JOIN COMPANY.DEPARTMENTS AS DEP
ON EMP.DEPARTMENT_ID = DEP.DEPARTMENT_ID;


