-- Joins
USE CLASSICMODELS;
-- FIND OUT THE CUSTOMER WHO HAVE NOT PLASED ANY ORDER.
SELECT C.CUSTOMERNAME, O.ORDERNUMBER FROM CUSTOMERS C INNER JOIN ORDERS O ON C.CUSTOMERNUMBER = O.CUSTOMERNUMBER 
WHERE O.ORDERNUMBER IS NULL;

-- FIND no of customers who have not placed from each country.

SELECT COUNTRY, CUSTOMERNAME,ORDERNUMBER,COUNT(CUSTOMERNUMBER) AS COUNT FROM CUSTOMERS INNER JOIN ORDERS ON CUSTOMERS.CUSTOMERNUMBER = ORDERS.CUSTOMERNUMBER
WHERE ORDERNUMBER = NULL
GROUP BY COUNTRY;


SELECT CUSTOMERNUMBER ,ORDERNUMBER,SUM(PRICEEACH*QUANTITYORDERED) AS TOTALVAL
FROM ORDERS JOIN ORDERDETAILS
USING(ORDERNUMBER)
GROUP BY CUSTOMERS;


SELECT COUNTRY,ORDERDATE,PRICEEACH,PRODUCTNAME 
FROM CUSTOMERS JOIN ORDERS USING(CUSTOMERNUMBER)
JOIN ORDERDETAILS USING(ORDERNUMBER) JOIN 
PRODUCTS USING(PRODUCTCODE);


SELECT COUNTRY,PRODUCTLINE,COUNT(PRODUCTLINE) AS K FROM CUSTOMERS JOIN ORDERS USING(CUSTOMERNUMBER)
JOIN ORDERDETAILS USING(ORDERNUMBER) JOIN 
PRODUCTS USING(PRODUCTCODE)
WHERE PRODUCTLINE = 'MOTORCYCLES'
group by COUNTRY,PRODUCTLINE
ORDER BY K DESC limit 1;


SELECT YEAR(ORDERDATE) AS YR,PRODUCTLINE,COUNT(ORDERDATE) AS K FROM CUSTOMERS JOIN ORDERS USING(CUSTOMERNUMBER)
JOIN ORDERDETAILS USING(ORDERNUMBER) JOIN 
PRODUCTS USING(PRODUCTCODE)
WHERE PRODUCTLINE = 'CLASSIC CARS'
group by YR,PRODUCTLINE
ORDER BY K DESC limit 1;

SELECT * FROM
(SELECT *,dense_rank() OVER(partition by COUNTRY ORDER BY CNT) AS DENSRANK FROM
(SELECT COUNTRY,CUSTOMERNAME, COUNT(ORDERNUMBER) AS CNT 
FROM CUSTOMERS JOIN ORDERS USING(CUSTOMERNUMBER)
GROUP BY COUNTRY,CUSTOMERNAME) AS D) AS DTH
WHERE DENSRANK <=2;


SELECT * FROM (
    SELECT 
        COUNTRY,
        CUSTOMERNAME,
        COUNT(ORDERNUMBER) AS CNT,
        DENSE_RANK() OVER (PARTITION BY COUNTRY ORDER BY COUNT(ORDERNUMBER)) AS DENSRANK
    FROM CUSTOMERS 
    JOIN ORDERS USING (CUSTOMERNUMBER)
    GROUP BY COUNTRY, CUSTOMERNAME
) AS DTH
WHERE DENSRANK <= 2;

