use swiggy;
select count(distinct city) as cities from restaurants order by cities ;

drop table sirsa_restaurants;
create table hyderabad_restaurants as select * from restaurants where city = 'hyderabad';
select * from hyderabad_restaurants;

-- for every restaurant highest cuisine revenue.
select name, cuisine,sum(cost*rating_count) as 'revenue'  from restaurants
group by name, cuisine
order by revenue desc;

-- no.of cuisines in every restaurant.
select name,count(distinct cuisine) as 'no_of_cuisines' from restaurants
group by name
order by no_of_cuisines desc;

-- List the Top 5 Cuisines by Revenue Generated by the Top 5 Restaurants of Every Cuisine.
select  cuisine,sum(cost*rating_count) as 'revenue'  from 
(select *,cost*rating_count,row_number() over(partition by cuisine order by cost*rating_count desc) as 'rank' from restaurants) as t
where t.rank<6
group by cuisine
order by revenue desc;

-- revenue generated by the top 1% of revenues.alter
select sum(revenue) as 'revenue' from 
(select cost*rating_count as 'revenue',row_number() over(ORDER BY cost * rating_count DESC) as 'rank' from restaurants) as t
where t.rank <= (select 0.01*count(name) from restaurants) ;

-- What is the revenue generated by the top 20% of the restaurants.
with q1 as
(select SUM(cost * rating_count) as 'top_revenue' from
(select cost*rating_count,row_number() over(order by cost*rating_count desc) as 'rank' from restaurants) as r
where r.rank <=12280),

q2 AS (
        SELECT SUM(cost * rating_count) AS 'total_revenue'
        FROM restaurants
    )
SELECT (top_revenue / total_revenue) * 100 AS 'revenue_percentage'
FROM q1, q2; 


WITH 
    q1 AS (
        SELECT SUM(cost * rating_count) AS 'top_revenue'
        FROM (
            SELECT *,
                   cost * rating_count,
                   ROW_NUMBER() OVER(ORDER BY cost * rating_count DESC) AS 'rank'
            FROM restaurants
        ) t
        WHERE t.rank <= 12280
    ),
    q2 AS (
        SELECT SUM(cost * rating_count) AS 'total_revenue'
        FROM restaurants
    )
SELECT (top_revenue / total_revenue) * 100 AS 'revenue_percentage'
FROM q1, q2;

